### ISSUE TITLE
Jamie's TODO List

### ISSUE THREAD

**Issue by j-mie** [HippieStation/HippieStationdeprecated2020#2931]
Anything you need me to do, post here.

- [x] Fix the PRMirrorer
- [x] Add webhook support to PRMirrorer
- [x] Upstream game rebase
- [x] Update the game SQL Schema
- [x] Update stats code
- [x] Update the stats SQL Schema
- [ ] A way to update/reboot the server from Discord
- [x] Kill the old Linux server

**Comment by ghost** [comment]
Map a singularity/tesla setup onto Meta so we can possibly add it into rotation?

**Comment by ghost** [comment]
@JamieH 

- A way to restart the entire VM from Discord
- A way to check if the VM/Host is still alive from Discord

**Comment by Pyko1** [comment]
@honkbot should handle the prepare maps for map merge

**Comment by j-mie** [comment]
TGS3 is now implemented, I can give accounts for this.
