### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by j-mie** [HippieStation/HippieStationdeprecated2020#553]
All priority ports are done.

Things to do in the future:
- [ ] Syndicate experiment teleporter | https://github.com/HippieStation/HippieStation13/pull/106
- [ ] Rapid crate sender? (Maybe) |  https://github.com/HippieStation/HippieStation13/pull/230
- [ ] Genetics overhaul? (Maybe) | https://github.com/HippieStation/HippieStation13/pull/204
- [x] Mindslave implants | https://github.com/HippieStation/HippieStation13/pull/313
- [x] Botany overhaul? (Maybe) | https://github.com/HippieStation/HippieStation13/pull/318
- [ ] Chainsaw sounds | https://github.com/HippieStation/HippieStation13/pull/394
- [ ] Chem tanks
- [ ] Honk cooler
- [ ] Deep frying mobs
- [ ] Skin colored butts
- [ ] Extra cloning pods
- [ ] Fix missing cameras in dorms

**Comment by Sarcalogo** [comment]
>1 of 47 after 30 days

JUST

**Comment by Scinexx** [comment]
Hey, I'd like to help out but I'd barely know what I'd be doing, any tips?

**Comment by j-mie** [comment]
@Scinexx hop on our Discord and ask in Coderbus: https://discord.gg/s8APu

**Comment by Sarcalogo** [comment]
You are taking too long. I am just going to do the rest of this (barring the ones I cannot do) myself.

**Comment by Uqualm** [comment]
Okay this will work. Now to do what you idiots cannot do yourselves.
